### ISSUE TITLE
Work-around for is_nothrow_copy_assignable_v with C++ < 17

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/mdarray#4]
[Line 82 of `const_wrapped_accessor_policy.hpp`](https://github.com/kokkos/mdarray/blob/f201c864ca208a296e320b3bdd89f82e99eee246/include/experimental/__p1684_bits/const_wrapped_accessor_policy.hpp#L82) uses `is_nothrow_copy_assignable_v<CP>`.  This was added in C++17.  If we aim for mdarray to build with earlier versions of C++, we could work around by using `is_nothrow_copy_assignable<CP>::value`.

Thanks to Piotr Luszczek for pointing this out!

**Comment by amklinv-nnl** [comment]
I'll work on this tomorrow.
